### ISSUE TITLE
Runtime compatibility issue

### ISSUE THREAD

**Issue by leelalagudu** [aws-cloudformation/cloudformation-cli-java-plugin#415]
**Summary**

Cannot get `mvn package` to succeed as it fails running tests with the below runtime incompatiblity error. 

`Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
        at org.jacoco.agent.rt.internal_035b120.asm.ClassReader.<init>(ClassReader.java:195)
        at org.jacoco.agent.rt.internal_035b120.asm.ClassReader.<init>(ClassReader.java:176)
        at org.jacoco.agent.rt.internal_035b120.asm.ClassReader.<init>(ClassReader.java:162)
        at org.jacoco.agent.rt.internal_035b120.core.internal.instr.InstrSupport.classReaderFor(InstrSupport.java:279)
        at org.jacoco.agent.rt.internal_035b120.core.instr.Instrumenter.instrument(Instrumenter.java:74)
        at org.jacoco.agent.rt.internal_035b120.core.instr.Instrumenter.instrument(Instrumenter.java:106)
        ... 65 more
`

My intelliJ IDE uses Oracle Open JDK 19.0.2 JDK for the project. My pom.xml has the below source and target compiler definitions

![image](https://user-images.githubusercontent.com/26421166/221516042-c4b491b4-bfd1-4da6-9f64-1844387bbf4e.png)

I specified the runtime in .rpdk-config as "java19". I am using protocolVersion 2.0.0

I had also tried skipping the tests and generating the package. However, my `sam local` tests were then failing , again due to the runtime incompatibility error. 

What are the recommended versions to set in each of these configs for this to work?

**Comment by mrinaudo-aws** [comment]
HI @leelalagudu - the values currently supported are those for Java 8 and Java 11 runtimes, that you can reference accordingly in the POM file and in the `.rpdk-config` file.
